name: ORDER INT | Publish Docker images

on:
  push:
    branches: [ main ]
    paths:
      - "src/order-integrations/**"
  pull_request:
    branches: [ main ]
    paths:
      - "src/order-integrations/**"
    

jobs:

  Publish-Document-to-Order:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ghcr.io/your-azure-coach/yac-order-integrations
        tags: latest
        
    - name: Build and push Docker image for Document to Order Logic App
      uses: docker/build-push-action@v2
      with:
        context: src/order-integrations
        file: src/order-integrations/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}